# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: hiperion_serras_development

test:
  <<: *default
  database: hiperion_serras_test

production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: hiperion_serras_production
    username: postgres
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV.fetch("DATABASE_HOST", "hiperionserras-db") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  cache:
    <<: *primary_production
    database: hiperion_serras_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hiperion_serras_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hiperion_serras_production_cable
    migrations_paths: db/cable_migrate
