service: vitalisvet

image: kayopereira/vitalisvet

servers:
  web:
    hosts:
      - 157.90.123.205

  job:
    hosts:
      - 157.90.123.205
    cmd: bundle exec good_job start

proxy:
  ssl: true
  hosts:
    - vitalisvet.com.br
    - www.vitalisvet.com.br
  app_port: 3000

registry:
  username: kayopereira
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - VITALIS_APP_DATABASE_USERNAME
  clear:
    JOB_CONCURRENCY: 1
    WEB_CONCURRENCY: 1
    POSTGRES_HOST: vitalisvet-db
    RAILS_SERVE_STATIC_FILES: true
    POSTGRES_USER: postgres
    POSTGRES_DB: vitalis_app_production
    REDIS_URL: "redis://157.90.123.205:6379/0"
    HOST: 0.0.0.0

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "vitalisvet_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max
    image: vitalisvet-cache

accessories:
  db:
    image: postgres:16
    host: 157.90.123.205
    port: 5432
    env: 
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: vitalis_app_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - infrastructure/postgres/postgresql.conf:/usr/local/share/postgresql/postgresql.conf.sample
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    host: 157.90.123.205
    port: 6379
    directories:
      - data:/data
    files:
      - infrastructure/redis/redis.conf:/etc/redis/redis.conf
      - infrastructure/redis/redis-sysctl.conf:/etc/sysctl.conf
    cmd: redis-server /etc/redis/redis.conf
